version: "3.3"
services:
  catalogs:
    build:
      dockerfile: Dockerfile
      context: .
    # ports:
    # - "13231:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalogs.rule=PathPrefix(`/catalogs`)"
      - "traefik.http.routers.catalogs.entrypoints=web"
      - "traefik.http.middlewares.catalogs-stripprefix.stripprefix.prefixes=/catalogs"
      - "traefik.http.routers.catalogs.middlewares=catalogs-stripprefix@docker"
      - "traefik.http.services.catalogs.loadbalancer.server.port=1323"
    networks:
      - insfras_default
networks:
  insfras_default:
    name: insfras_default
    external: true